kind: Template
apiVersion: v1
metadata:
  name: Nextcloute
  annotations:
    description: >-
      Platilla de despliegue para Nextcloud
    tags: "nestjs,typescript"
    openshift.io/documentation-url: "https://github.com/DanielBortot/proyecto-cn-nextcloud"
    openshift.io/suport-url: "https://github.com/DanielBortot/proyecto-cn-nextcloud"

parameters:
  - name: APP_NAME
    description: Nombre de applicación (Prefijo de todos los objetos).
    required: true

  - name: MYSQL_ROOT_PASSWORD
    description: Password de root de la base de datos.
    required: true

  - name: MYSQL_PASSWORD
    description: Password de usuario para conexión a la base de datos.
    required: true

  - name: MYSQL_DATABASE
    description: Nombre de la base de datos.
    required: true

  - name: MYSQL_USER
    description: Nombre del usuario.
    required: true

  - name: MYSQL_HOST
    description: Host base de datos.
    required: true

  - name: DOMAIN_NAME
    description: Nombre de dominio para la publicación de la ruta.
    required: true

  - name: PROJECT_NAME
    description: Nombre de projecto
    required: true

#  - name: IMAGE_NAME
#    required: true

labels:
  app: "${APP_NAME}"

objects:

  - kind: Secret
    apiVersion: v1
    metadata:
      name: "${APP_NAME}-keys"
    type: Opaque
    stringData:
      db_root_password: '${MYSQL_ROOT_PASSWORD}'
      db_password: '${MYSQL_PASSWORD}'
      db_user: '${MYSQL_USER}'
      db_database: '${MYSQL_DATABASE}'

  - kind: Service
    apiVersion: v1
    metadata:
      name: "${APP_NAME}-nextcloud"
    spec:
      ports:
        - name: nextcloud
          port: 8080
          targetPort: 8080
      selector:
        name: "${APP_NAME}-nextcloud"

  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: "${APP_NAME}-nextcloud"
      name: "${APP_NAME}-nextcloud"
    spec:
      host: ${DOMAIN_NAME}
      port:
        targetPort: nextcloud
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: "${APP_NAME}-nextcloud"
        weight: 100
      wildcardPolicy: None

  - apiVersion: v1
    kind: Service
    metadata:
      name: '${APP_NAME}-mariadb'
    spec:
      type: ClusterIP
      ports:
        - name: mariadb
          port: 3306
          protocol: TCP
          targetPort: 3306
      selector:
        name: '${APP_NAME}-mariadb'

  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: '${APP_NAME}-mariadb'
    spec:
      replicas: 1
      selector:
        name: ${APP_NAME}-mariadb
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            name: "${APP_NAME}-mariadb"
        spec:
          containers:
            - env:
              - name: MYSQL_USER
                valueFrom:
                  secretKeyRef:
                    name: "${APP_NAME}-keys"
                    key: db_user

              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: "${APP_NAME}-keys"
                    key: db_password

              - name: MYSQL_ROOT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: "${APP_NAME}-keys"
                    key: db_root_password

              - name: MYSQL_DATABASE
                valueFrom:
                  secretKeyRef:
                    name: "${APP_NAME}-keys"
                    key: db_database

              image: ' '
              imagePullPolicy: Always
              name: mariadb
              ports:
                - containerPort: 3306
                  protocol: TCP
              resources:
                limits:
                  memory: "1G"
                requests:
                  memory: "1G"
              volumeMounts:
                - mountPath: /var/lib/mysql 
                  name: maria-data
                  subPath: maria-data
          restartPolicy: Always
          securityContext:
            supplementalGroups:
              - 5688
          volumes:
            - name: maria-data
              persistentVolumeClaim:
                claimName: "data"
      test: false
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - mariadb
            from:
              kind: ImageStreamTag
              name: 'mariadb:10.3'
              namespace: 'openshift'
            lastTriggeredImage: ''
          type: ImageChange
        - type: ConfigChange

  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: "${APP_NAME}-nextcloud"
    spec:
      replicas: 1
      selector:
        name: "${APP_NAME}-nextcloud"
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            app: "${APP_NAME}-nextcloud"
            name: "${APP_NAME}-nextcloud"
        spec:
          containers:
            - env:
                - name: MYSQL_HOST
                  value: "${MYSQL_HOST}"

                - name: MYSQL_USER
                  value: "${MYSQL_USER}"

                - name: MYSQL_DATABASE
                  value: "${MYSQL_DATABASE}"

                - name: MYSQL_PASSWORD
                  value: "${MYSQL_ROOT_PASSWORD}"
              image: ' '
              imagePullPolicy: Always
              name: nextcloud
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources:
                limits:
                  memory: "1G"
                requests:
                  memory: "1G"
              volumeMounts:
                - mountPath: /var/www/html 
                  name: nextcloud-data
                  subPath: nextcloud-data
          restartPolicy: Always
          securityContext:
            supplementalGroups:
              - 5688
          volumes:
            - name: nextcloud-data
              persistentVolumeClaim:
                claimName: "data"
      test: false
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - nextcloud
            from:
              kind: ImageStreamTag
              name: 'nextcloud-okd:stable2'
              namespace: 'dabortot-21'
            lastTriggeredImage: ''
          type: ImageChange
        - type: ConfigChange
